/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorUsuario;
import Controlador.SesionUsuario;
import DTOs.UsuarioDTO;
import Modelo.RolUsuario;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/**
 *
 * @author je110
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    public FrmMenuPrincipal() {
        initComponents();
        DesktopPane.setLayer(pnlLabelFondo, Integer.MIN_VALUE);
        ajustarImagenFondo();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    public void inicializarDespuesDeLogin() {
        configurarAccesoPorRol();
        actualizarInfoUsuario();
    }
    
    private void ajustarImagenFondo() {
        ImageIcon imagenOriginal = new ImageIcon(getClass().getResource("/Icons/ProduccionAgricola.jpg"));
        Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(DesktopPane.getWidth(),DesktopPane.getHeight(),Image.SCALE_AREA_AVERAGING);
        lblFondo.setIcon(new ImageIcon(imagenEscalada));
    }

    public void abrirVentana(JInternalFrame frame) {
        if (!frame.isVisible()) {
            DesktopPane.add(frame);
            frame.setVisible(true);
        }
        try {
            frame.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void configurarAccesoPorRol() {
        SesionUsuario sesion = SesionUsuario.getInstance();
    
        if (!sesion.haySesionActiva()) {
            JOptionPane.showMessageDialog(this,"No hay sesión activa. El sistema se cerrará.","Error",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }
    
        UsuarioDTO usuario = sesion.getUsuarioActual();
    
        if (usuario.getRol() == RolUsuario.TRABAJADOR) {

            mnTrabajadores.setEnabled(false);
            mnUsuarios.setEnabled(false);

            mnTrabajadores.setForeground(Color.GRAY);
            mnUsuarios.setForeground(Color.GRAY);

            mnTrabajadores.setToolTipText("⚠️ Acceso restringido - Solo Administradores");
            mnUsuarios.setToolTipText("⚠️ Acceso restringido - Solo Administradores");
        
            System.out.println("✓ Acceso configurado para TRABAJADOR: " + usuario.getNombreCompleto()); 
        } else if (usuario.getRol() == RolUsuario.ADMINISTRADOR) {

            mnTrabajadores.setEnabled(true);
            mnUsuarios.setEnabled(true);
        
            System.out.println("✓ Acceso configurado para ADMINISTRADOR: " + usuario.getNombreCompleto());
        }
    }

    private void actualizarInfoUsuario() {
        SesionUsuario sesion = SesionUsuario.getInstance();
        UsuarioDTO usuario = sesion.getUsuarioActual();
    
        if (usuario != null) {
            String textoUsuario = "👤 " + usuario.getNombreCompleto() + " (" + usuario.getRol().name() + ")";InfoUsuario.setText(textoUsuario);
        }
    }  

    private void cerrarSesion() {
        int confirmacion = JOptionPane.showConfirmDialog(this,"¿Está seguro que desea cerrar sesión?","Confirmar cierre de sesión",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    
        if (confirmacion == JOptionPane.YES_OPTION) {

            SesionUsuario.getInstance().cerrarSesion();
        
            this.dispose();
        
            SwingUtilities.invokeLater(() -> {
                JdlLogin login = new JdlLogin(null, true);
                login.setVisible(true);

                if (!SesionUsuario.getInstance().haySesionActiva()) {
                    System.exit(0);
                } else {
                    new FrmMenuPrincipal().setVisible(true);
                }
            });
        }
    }

    private void salirSistema() {
        int confirmacion = JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir del sistema?","Confirmar salida",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    
        if (confirmacion == JOptionPane.YES_OPTION) {
            SesionUsuario.getInstance().cerrarSesion();
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        pnlLabelFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        mnbarraSistema = new javax.swing.JMenuBar();
        mnSistemaProducciónAgricola = new javax.swing.JMenu();
        mnCultivos = new javax.swing.JMenuItem();
        mnTrabajadores = new javax.swing.JMenuItem();
        mnProduccion = new javax.swing.JMenuItem();
        mnAlmacen = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenuItem();
        mnPerfil = new javax.swing.JMenu();
        InfoUsuario = new javax.swing.JMenuItem();
        mnCerrarSesion = new javax.swing.JMenuItem();
        mnSalirSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                DesktopPaneComponentResized(evt);
            }
        });

        pnlLabelFondo.setLayout(new java.awt.BorderLayout(658, 380));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ProduccionAgricola.jpg"))); // NOI18N
        pnlLabelFondo.add(lblFondo, java.awt.BorderLayout.CENTER);

        DesktopPane.setLayer(pnlLabelFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnSistemaProducciónAgricola.setText("Sistema de Producción Agricola");
        mnSistemaProducciónAgricola.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnSistemaProducciónAgricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSistemaProducciónAgricolaActionPerformed(evt);
            }
        });

        mnCultivos.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnCultivos.setText("Cultivos");
        mnCultivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCultivosActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnCultivos);

        mnTrabajadores.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnTrabajadores.setText("Trabajadores");
        mnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTrabajadoresActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnTrabajadores);

        mnProduccion.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnProduccion.setText("Producción");
        mnProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProduccionActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnProduccion);

        mnAlmacen.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnAlmacen.setText("Almacen");
        mnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlmacenActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnAlmacen);

        mnUsuarios.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnUsuarios.setText("Usuarios");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnUsuarios);

        mnbarraSistema.add(mnSistemaProducciónAgricola);

        mnPerfil.setText("Perfil");
        mnPerfil.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        InfoUsuario.setText("Usuario");
        InfoUsuario.setEnabled(false);
        mnPerfil.add(InfoUsuario);

        mnCerrarSesion.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnCerrarSesion.setText("Cerrar Sesión");
        mnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarSesionActionPerformed(evt);
            }
        });
        mnPerfil.add(mnCerrarSesion);

        mnSalirSistema.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        mnSalirSistema.setText("Salir del Sistema");
        mnSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirSistemaActionPerformed(evt);
            }
        });
        mnPerfil.add(mnSalirSistema);

        mnbarraSistema.add(mnPerfil);

        setJMenuBar(mnbarraSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCultivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCultivosActionPerformed
        IntFrmCultivo internalFrameCultivo = new IntFrmCultivo();
        DesktopPane.add(internalFrameCultivo);
        internalFrameCultivo.setVisible(true);
    }//GEN-LAST:event_mnCultivosActionPerformed

    private void DesktopPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DesktopPaneComponentResized
        ajustarImagenFondo();
    }//GEN-LAST:event_DesktopPaneComponentResized

    private void mnProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProduccionActionPerformed
        IntFrmProduccion internalFrameProduccion = new IntFrmProduccion();
        DesktopPane.add(internalFrameProduccion);
        internalFrameProduccion.setVisible(true);
    }//GEN-LAST:event_mnProduccionActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        IntFrmUsuario internalFrameUsuario = new IntFrmUsuario();
        DesktopPane.add(internalFrameUsuario);
        internalFrameUsuario.setVisible(true);
    }//GEN-LAST:event_mnUsuariosActionPerformed

    private void mnSistemaProducciónAgricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSistemaProducciónAgricolaActionPerformed
        
    }//GEN-LAST:event_mnSistemaProducciónAgricolaActionPerformed

    private void mnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlmacenActionPerformed
        IntFrmAlmacen internalFrameAlmacen = new IntFrmAlmacen();
        DesktopPane.add(internalFrameAlmacen);
        internalFrameAlmacen.setVisible(true);
    }//GEN-LAST:event_mnAlmacenActionPerformed

    private void mnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarSesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_mnCerrarSesionActionPerformed

    private void mnSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirSistemaActionPerformed
        salirSistema();
    }//GEN-LAST:event_mnSalirSistemaActionPerformed

    private void mnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTrabajadoresActionPerformed
        IntFrmTrabajador internalFrameTrabajador = new IntFrmTrabajador();
        DesktopPane.add(internalFrameTrabajador);
        internalFrameTrabajador.setVisible(true);
    }//GEN-LAST:event_mnTrabajadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        
        try {

            Controlador.ControladorUsuario controlador = new Controlador.ControladorUsuario();
            boolean hayUsuarios = controlador.existenUsuarios();
            
            if (!hayUsuarios) {
                JOptionPane.showMessageDialog(menu,
                    "No hay usuarios registrados en el sistema.\n" +
                    "Por favor, registre al menos un usuario administrador.",
                    "Primer uso del sistema",
                    JOptionPane.INFORMATION_MESSAGE);
                
                IntFrmUsuario frmRegistro = new IntFrmUsuario();
                frmRegistro.configurarPrimerRegistro();
                menu.abrirVentana(frmRegistro);
                
            } else {
                JdlLogin login = new JdlLogin(menu, true);
                login.setLocationRelativeTo(menu);
                login.setVisible(true);
                
                if (!Controlador.SesionUsuario.getInstance().haySesionActiva()) {
                    JOptionPane.showMessageDialog(menu,
                        "No hay sesión activa. El sistema se cerrará.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                } else {
                    menu.inicializarDespuesDeLogin();
                }
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(menu,
                "Error al verificar usuarios: " + ex.getMessage(),
                "Error de sistema",
                JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error verificando usuarios", ex);
            System.exit(1);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem InfoUsuario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuItem mnAlmacen;
    private javax.swing.JMenuItem mnCerrarSesion;
    private javax.swing.JMenuItem mnCultivos;
    private javax.swing.JMenu mnPerfil;
    private javax.swing.JMenuItem mnProduccion;
    private javax.swing.JMenuItem mnSalirSistema;
    private javax.swing.JMenu mnSistemaProducciónAgricola;
    private javax.swing.JMenuItem mnTrabajadores;
    private javax.swing.JMenuItem mnUsuarios;
    private javax.swing.JMenuBar mnbarraSistema;
    private javax.swing.JPanel pnlLabelFondo;
    // End of variables declaration//GEN-END:variables
}
