/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author je110
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());
    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        DesktopPane.setLayer(pnlLabelFondo, Integer.MIN_VALUE);
        ajustarImagenFondo();
    }
    
    private void ajustarImagenFondo() {
        ImageIcon imagenOriginal = new ImageIcon(getClass().getResource("/Icons/ProduccionAgricola.jpg"));
        Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(
            DesktopPane.getWidth(),
            DesktopPane.getHeight(),
            Image.SCALE_AREA_AVERAGING
        );
        lblFondo.setIcon(new ImageIcon(imagenEscalada));
    }

    public void abrirVentana(JInternalFrame frame) {
        if (!frame.isVisible()) {
            DesktopPane.add(frame);
            frame.setVisible(true);
        }
        try {
            frame.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        pnlLabelFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        mnbarraSistema = new javax.swing.JMenuBar();
        mnSistemaProducciónAgricola = new javax.swing.JMenu();
        mnCultivos = new javax.swing.JMenuItem();
        mnTrabajadores = new javax.swing.JMenuItem();
        mnProduccion = new javax.swing.JMenuItem();
        mnAlmacen = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                DesktopPaneComponentResized(evt);
            }
        });

        pnlLabelFondo.setLayout(new java.awt.BorderLayout(658, 380));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ProduccionAgricola.jpg"))); // NOI18N
        pnlLabelFondo.add(lblFondo, java.awt.BorderLayout.CENTER);

        DesktopPane.setLayer(pnlLabelFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnSistemaProducciónAgricola.setText("Sistema de Producción Agricola");

        mnCultivos.setText("Cultivos");
        mnCultivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCultivosActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnCultivos);

        mnTrabajadores.setText("Trabajadores");
        mnSistemaProducciónAgricola.add(mnTrabajadores);

        mnProduccion.setText("Producción");
        mnProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProduccionActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnProduccion);

        mnAlmacen.setText("Almacen");
        mnSistemaProducciónAgricola.add(mnAlmacen);

        mnUsuarios.setText("Usuarios");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        mnSistemaProducciónAgricola.add(mnUsuarios);

        mnbarraSistema.add(mnSistemaProducciónAgricola);

        setJMenuBar(mnbarraSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCultivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCultivosActionPerformed
        IntFrmCultivos internalFrameCultivo = new IntFrmCultivos();
        DesktopPane.add(internalFrameCultivo);
        internalFrameCultivo.setVisible(true);
    }//GEN-LAST:event_mnCultivosActionPerformed

    private void DesktopPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DesktopPaneComponentResized
        ajustarImagenFondo();
    }//GEN-LAST:event_DesktopPaneComponentResized

    private void mnProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProduccionActionPerformed
        IntFrmProduccion internalFrameProduccion = new IntFrmProduccion();
        DesktopPane.add(internalFrameProduccion);
        internalFrameProduccion.setVisible(true);
    }//GEN-LAST:event_mnProduccionActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        IntFrmUsuario internalFrameUsuario = new IntFrmUsuario();
        DesktopPane.add(internalFrameUsuario);
        internalFrameUsuario.setVisible(true);
    }//GEN-LAST:event_mnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuItem mnAlmacen;
    private javax.swing.JMenuItem mnCultivos;
    private javax.swing.JMenuItem mnProduccion;
    private javax.swing.JMenu mnSistemaProducciónAgricola;
    private javax.swing.JMenuItem mnTrabajadores;
    private javax.swing.JMenuItem mnUsuarios;
    private javax.swing.JMenuBar mnbarraSistema;
    private javax.swing.JPanel pnlLabelFondo;
    // End of variables declaration//GEN-END:variables
}
