/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAlmacen;
import DTOs.AlmacenDTO;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samue
 */
public class IntFrmAlertas extends javax.swing.JInternalFrame {
    
    private final ControladorAlmacen controlador;
    
    /**
     * Creates new form IntFrmAlertas
     */
    public IntFrmAlertas(ControladorAlmacen controlador) {
        initComponents();
        this.controlador = controlador;
         cargarAlertas();
    }
    
    private void cargarAlertas() {
         DefaultTableModel model = (DefaultTableModel) TbtTablaAlmacenAlertas.getModel();
    model.setRowCount(0);

    // Aseguramos columnas
    if (model.getColumnCount() < 8) { 
        model.setColumnIdentifiers(new Object[]{"ID", "Prod ID", "Cantidad", "F. Ingreso", "F. Egreso", "Días Total", "Días Extra", "Estado"});
    }

    try {
        List<AlmacenDTO> lista = controlador.listarAlmacenes();
        LocalDate hoy = LocalDate.now();
        int diasLimite = 30; 

        for (AlmacenDTO a : lista) {
            
            // --- INICIO CORRECCIÓN DE FECHAS ---
            long diasTotal = 0;
            
            // 1. Imprimir en consola para ver qué trae la base de datos (MIRA LA CONSOLA DE NETBEANS)
            System.out.println("Producto ID: " + a.getId() + " | Fecha en DTO: " + a.getFechaIngreso());

            if (a.getFechaIngreso() != null) {
                // 2. Conversión explícita segura
                // Asumimos que getFechaIngreso() devuelve java.sql.Date o java.util.Date
                // Lo convertimos a String y luego a LocalDate para evitar errores de tipos
                String fechaStr = a.getFechaIngreso().toString(); // Formato esperado: yyyy-MM-dd
                LocalDate fechaIngresoLocal = LocalDate.parse(fechaStr);
                
                // 3. Calculamos la diferencia
                diasTotal = java.time.temporal.ChronoUnit.DAYS.between(fechaIngresoLocal, hoy);
            }
            // --- FIN CORRECCIÓN ---

            if (diasTotal < 0) diasTotal = 0;

            long diasDeMas = 0;
            if (diasTotal > diasLimite) {
                diasDeMas = diasTotal - diasLimite;
            }

            Object[] fila = new Object[]{
                a.getId(),
                a.getProduccionId(),
                a.getCantidadDisponible(),
                a.getFechaIngreso(),
                a.getFechaEgreso(),
                diasTotal,   
                diasDeMas,   
                a.getEstado()
            };

            model.addRow(fila);
        }

        // Renderer para pintar de ROJO
        TbtTablaAlmacenAlertas.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                try {
                    // Verificamos columna 5 (Días Total)
                    Object valDias = table.getValueAt(row, 5); 
                    if (valDias != null) {
                        long dias = Long.parseLong(valDias.toString());
                        if (dias > diasLimite) {
                            c.setBackground(java.awt.Color.RED);
                            c.setForeground(java.awt.Color.WHITE);
                        } else {
                            c.setBackground(java.awt.Color.WHITE);
                            c.setForeground(java.awt.Color.BLACK);
                        }
                    }
                } catch (Exception ex) { }
                
                if (isSelected) {
                    c.setBackground(table.getSelectionBackground());
                    c.setForeground(table.getSelectionForeground());
                }
                return c;
            }
        });

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbtTablaAlmacenAlertas = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 5));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setBackground(new java.awt.Color(0, 204, 153));
        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Grafica.png"))); // NOI18N
        jLabel1.setText("Productos Almacenados Por Tiempo");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setOpaque(true);

        TbtTablaAlmacenAlertas.setBackground(new java.awt.Color(153, 255, 204));
        TbtTablaAlmacenAlertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "ProduccionId", "Cantidad", "FechaIngreso", "FechaEgreso", "Dias en Almacen", "Estado"
            }
        ));
        jScrollPane1.setViewportView(TbtTablaAlmacenAlertas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbtTablaAlmacenAlertas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
